import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Scene from "../src/components/Scene";

const Home: NextPage = () => {


  return (
    <div className={styles.container}>
      <Head>
        <title>ThreeJS and Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Scenen created with React, NextJS and Three</h3>
        <Scene />
      </main>

    </div>
  )
}

export default Home
